title: rotarydrone
description: "Hunting and Phishing"
author:
  name: "rotarydrone"
  email: "rotarydrone@protonmail.com"
  url: "https://www.knotwork.io"

baseurl: /

source: .
destination: ./_site
permalink: /:categories/:title/
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "rotarydrone"
year : "2019"
